version: '3'
services:
  wordpress:
    image: {{APP_IMAGE_NAME_TAG}}
    env_file:
      - .env
    ports:
      - ${HOST_PORT:-3000}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      WORDPRESS_DB_DATABASE: ${DB_DATABASE}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_SITEURL', '${SERVER_URL}' );
        define('WP_HOME', '${SERVER_URL}' );
        define('FORCE_SSL_ADMIN', true);
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-{{OIDC_CLIENT_ID}}}
      OIDC_ENDPOINT_LOGIN_URL: ${OIDC_ENDPOINT_LOGIN_URL:-{{OIDC_ENDPOINT_LOGIN_URL}}}
      OIDC_ENDPOINT_USERINFO_URL: ${OIDC_ENDPOINT_USERINFO_URL:-{{OIDC_ENDPOINT_USERINFO_URL}}}
      OIDC_ENDPOINT_TOKEN_URL: ${OIDC_ENDPOINT_TOKEN_URL:-{{OIDC_ENDPOINT_TOKEN_URL}}}
      OIDC_ENDPOINT_LOGOUT_URL: ${OIDC_ENDPOINT_LOGOUT_URL:-{{OIDC_ENDPOINT_LOGOUT_URL}}}
      OIDC_CLIENT_SCOPE: ${OIDC_CLIENT_SCOPE:-{{OIDC_CLIENT_SCOPE}}}
      OIDC_LOGIN_TYPE: ${OIDC_LOGIN_TYPE:-{{OIDC_LOGIN_TYPE}}}
      OIDC_CREATE_IF_DOES_NOT_EXIST: ${OIDC_CREATE_IF_DOES_NOT_EXIST:-{{OIDC_CREATE_IF_DOES_NOT_EXIST}}}
      OIDC_LINK_EXISTING_USERS: ${OIDC_LINK_EXISTING_USERS:-{{OIDC_LINK_EXISTING_USERS}}}
      OIDC_REDIRECT_USER_BACK: ${OIDC_REDIRECT_USER_BACK:-{{OIDC_REDIRECT_USER_BACK}}}
      OIDC_ENFORCE_PRIVACY: ${OIDC_ENFORCE_PRIVACY:-{{OIDC_ENFORCE_PRIVACY}}}
      FORMINATOR_ADDON_RT_HOST: ${FORMINATOR_ADDON_RT_HOST:-{{FORMINATOR_ADDON_RT_HOST}}}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - uploads-data:/usr/src/wordpress/wp-content/uploads
      - wp-logs-data:{{WP_LOG_ROOT}}

  backup:
    image: {{APP_UTILS_IMAGE_NAME_TAG}}
    env_file:
      - .env
    environment:
      GC_BUCKET_BACKUPS: ${GC_BUCKET_BACKUPS:-{{GC_BUCKET_BACKUPS}}}
      BACKUP_FILE_NAME: ${BACKUP_FILE_NAME:-{{BACKUP_FILE_NAME}}}
      UPLOADS_FILE_NAME: ${UPLOADS_FILE_NAME:-{{UPLOADS_FILE_NAME}}}
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      WORDPRESS_DB_DATABASE: ${DB_DATABASE}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
      - wordpress
    volumes:
      - uploads-data:/uploads
      - ./writer-key.json:/etc/service-account.json
    command: "./backup/entrypoint.sh"

  init:
    image: {{APP_UTILS_IMAGE_NAME_TAG}}
    env_file:
      - .env
    environment:
      SERVER_URL: ${SERVER_URL}
      GC_BUCKET_BACKUPS: ${GC_BUCKET_BACKUPS:-{{GC_BUCKET_BACKUPS}}}
      BACKUP_FILE_NAME: ${BACKUP_FILE_NAME:-{{BACKUP_FILE_NAME}}}
      UPLOADS_FILE_NAME: ${UPLOADS_FILE_NAME:-{{UPLOADS_FILE_NAME}}}
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      WORDPRESS_DB_DATABASE: ${DB_DATABASE}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
      - wordpress
    volumes:
      - uploads-data:/uploads
      - ./reader-key.json:/etc/service-account.json
    command: ./init/init.sh

  db:
    image: {{MYSQL_IMAGE_NAME_TAG}}
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ulimits:
      nofile:
        soft: 262114
        hard: 262114

volumes:
  db-data:
  uploads-data:
  wp-logs-data:
