version: '3'
services:
  wordpress:
    image: gcr.io/digital-ucdavis-edu/itis-wp-rt-forms:v1.0.0
    env_file:
      - .env
    ports:
      - ${HOST_PORT:-3000}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_SITEURL', '${SERVER_URL}' );
        define('WP_HOME', '${SERVER_URL}' );
        define('FORCE_SSL_ADMIN', true);
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-rt-forms-client}
      OIDC_ENDPOINT_LOGIN_URL: ${OIDC_ENDPOINT_LOGIN_URL:-https://auth.library.ucdavis.edu/realms/internal/protocol/openid-connect/auth}
      OIDC_ENDPOINT_USERINFO_URL: ${OIDC_ENDPOINT_USERINFO_URL:-https://auth.library.ucdavis.edu/realms/internal/protocol/openid-connect/userinfo}
      OIDC_ENDPOINT_TOKEN_URL: ${OIDC_ENDPOINT_TOKEN_URL:-https://auth.library.ucdavis.edu/realms/internal/protocol/openid-connect/token}
      OIDC_ENDPOINT_LOGOUT_URL: ${OIDC_ENDPOINT_LOGOUT_URL:-https://auth.library.ucdavis.edu/realms/internal/protocol/openid-connect/logout}
      OIDC_CLIENT_SCOPE: ${OIDC_CLIENT_SCOPE:-openid profile email roles}
      OIDC_LOGIN_TYPE: ${OIDC_LOGIN_TYPE:-auto}
      OIDC_CREATE_IF_DOES_NOT_EXIST: ${OIDC_CREATE_IF_DOES_NOT_EXIST:-true}
      OIDC_LINK_EXISTING_USERS: ${OIDC_LINK_EXISTING_USERS:-true}
      OIDC_REDIRECT_USER_BACK: ${OIDC_REDIRECT_USER_BACK:-true}
      OIDC_ENFORCE_PRIVACY: ${OIDC_ENFORCE_PRIVACY:-true}
      FORMINATOR_ADDON_RT_HOST: ${FORMINATOR_ADDON_RT_HOST:-https://rt.lib.ucdavis.edu}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - uploads-data:/usr/src/wordpress/wp-content/uploads
      - wp-logs-data:/var/log/wordpress

  backup:
    image: gcr.io/digital-ucdavis-edu/itis-wp-rt-forms-utils:v1.0.0
    env_file:
      - .env
    environment:
      GC_BUCKET_BACKUPS: ${GC_BUCKET_BACKUPS:-itis-backups/wp-rt-forms}
      BACKUP_FILE_NAME: ${BACKUP_FILE_NAME:-db.sql.gz}
      UPLOADS_FILE_NAME: ${UPLOADS_FILE_NAME:-uploads.tar.gz}
    depends_on:
      - db
      - wordpress
    volumes:
      - uploads-data:/uploads
      - ./writer-key.json:/etc/service-account.json
    command: "./backup/entrypoint.sh"

  init:
    image: gcr.io/digital-ucdavis-edu/itis-wp-rt-forms-utils:v1.0.0
    env_file:
      - .env
    environment:
      GC_BUCKET_BACKUPS: ${GC_BUCKET_BACKUPS:-itis-backups/wp-rt-forms}
      BACKUP_FILE_NAME: ${BACKUP_FILE_NAME:-db.sql.gz}
      UPLOADS_FILE_NAME: ${UPLOADS_FILE_NAME:-uploads.tar.gz}
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
    depends_on:
      - db
      - wordpress
    volumes:
      - uploads-data:/uploads
      - ./reader-key.json:/etc/service-account.json
    command: ./init/init.sh

  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    ulimits:
      nofile:
        soft: 262114
        hard: 262114

volumes:
  db-data:
  uploads-data:
  wp-logs-data:
