x-variables:
  main-image: &main-image us-west1-docker.pkg.dev/digital-ucdavis-edu/wordpress/wp-rt-forms:v1.5.0
  utils-image: &utils-image us-west1-docker.pkg.dev/digital-ucdavis-edu/wordpress/wp-rt-forms-utils:v1.5.0

services:
  wordpress:
    image: *main-image
    env_file:
      - .env
    ports:
      - ${HOST_PORT:-3000}:80
    restart: always
    environment:
      SERVER_URL: ${SERVER_URL:-https://support.staff.library.ucdavis.edu}
      UCD_THEME_ENV: ${UCD_THEME_ENV:-prod}
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      WORDPRESS_DB_DATABASE: ${DB_DATABASE:-wordpress}
      WORDPRESS_DB_USER: ${DB_USER:-wordpress}
      WORDPRESS_CONFIG_EXTRA: |
        define('FORCE_SSL_ADMIN', true);
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-rt-forms-client}
      OIDC_ENDPOINT_LOGIN_URL: ${OIDC_ENDPOINT_LOGIN_URL:-https://auth.library.ucdavis.edu/realms/internal/protocol/openid-connect/auth}
      OIDC_ENDPOINT_USERINFO_URL: ${OIDC_ENDPOINT_USERINFO_URL:-}
      OIDC_ENDPOINT_TOKEN_URL: ${OIDC_ENDPOINT_TOKEN_URL:-https://auth.library.ucdavis.edu/realms/internal/protocol/openid-connect/token}
      OIDC_ENDPOINT_LOGOUT_URL: ${OIDC_ENDPOINT_LOGOUT_URL:-https://auth.library.ucdavis.edu/realms/internal/protocol/openid-connect/logout}
      OIDC_CLIENT_SCOPE: ${OIDC_CLIENT_SCOPE:-openid profile email roles}
      OIDC_LOGIN_TYPE: ${OIDC_LOGIN_TYPE:-auto}
      OIDC_CREATE_IF_DOES_NOT_EXIST: ${OIDC_CREATE_IF_DOES_NOT_EXIST:-true}
      OIDC_LINK_EXISTING_USERS: ${OIDC_LINK_EXISTING_USERS:-true}
      OIDC_REDIRECT_USER_BACK: ${OIDC_REDIRECT_USER_BACK:-true}
      OIDC_ENFORCE_PRIVACY: ${OIDC_ENFORCE_PRIVACY:-true}
      FORMINATOR_ADDON_RT_HOST: ${FORMINATOR_ADDON_RT_HOST:-https://rt.lib.ucdavis.edu}
      UCDLIB_PERSONNEL_API_URL: ${UCDLIB_PERSONNEL_API_URL:-https://iam.staff.library.ucdavis.edu/json}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - uploads-data:/usr/src/wordpress/wp-content/uploads
      - wp-logs-data:/var/log/wordpress

  backup:
    image: *utils-image
    restart: always
    env_file:
      - .env
    environment:
      RUN_BACKUP: 'true'
      BACKUP_DATA_ENV: ${BACKUP_DATA_ENV:-prod}
      SERVER_URL: ${SERVER_URL:-https://support.staff.library.ucdavis.edu}
      GC_BUCKET_BACKUPS: ${GC_BUCKET_BACKUPS:-itis-backups/wp-rt-forms}
      BACKUP_FILE_NAME: ${BACKUP_FILE_NAME:-db.sql.gz}
      UPLOADS_FILE_NAME: ${UPLOADS_FILE_NAME:-uploads.tar.gz}
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      WORDPRESS_DB_DATABASE: ${DB_DATABASE:-wordpress}
      WORDPRESS_DB_USER: ${DB_USER:-wordpress}
    depends_on:
      - db
      - wordpress
    volumes:
      - uploads-data:/uploads
      - ../../secrets/writer-key.json:/etc/service-account.json
    command: "./backup/entrypoint.sh"

  init:
    image: *utils-image
    env_file:
      - .env
    environment:
      RUN_INIT: "true"
      INIT_DATA_ENV: ${INIT_DATA_ENV:-prod}
      SERVER_URL: ${SERVER_URL:-https://support.staff.library.ucdavis.edu}
      GC_BUCKET_BACKUPS: ${GC_BUCKET_BACKUPS:-itis-backups/wp-rt-forms}
      BACKUP_FILE_NAME: ${BACKUP_FILE_NAME:-db.sql.gz}
      UPLOADS_FILE_NAME: ${UPLOADS_FILE_NAME:-uploads.tar.gz}
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      WORDPRESS_DB_DATABASE: ${DB_DATABASE:-wordpress}
      WORDPRESS_DB_USER: ${DB_USER:-wordpress}
    depends_on:
      - db
      - wordpress
    volumes:
      - uploads-data:/uploads
      - ../../secrets/reader-key.json:/etc/service-account.json
    command: ./init/init.sh

  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-wordpress}
      MYSQL_USER: ${DB_USER:-wordpress}
    volumes:
      - db-data:/var/lib/mysql
    ulimits:
      nofile:
        soft: 262114
        hard: 262114

volumes:
  db-data:
  uploads-data:
  wp-logs-data:
